#端口设置
server:
  port: 8080
  servlet:
    context-path: /community

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #数据库连接池
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  #关闭thymeleaf缓存
  thymeleaf:
    cache: false
#    邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 1711293190@qq.com
    password: wpqifrmvjeaceeee
    protocol: smtps
    properties.mail.smtp.ssl.enable: true

  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #自动生成id
    use-generated-keys: true
  type-aliases-package: com.mxb.community.domain
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mappers/*.xml

#自定义键值对
community.path.domain: http://localhost:8080
community.path.upload: d:/work/data/upload









